package com.springboot.libraryOrg;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.springboot.libraryOrg.models.Books;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called booksRepository which is auto-generated by Spring, we will use it to handle the data
	private BooksRepository booksRepository;

 	@PostMapping(path="/add") // Map ONLY POST Requests
 	public @ResponseBody String addNewBook (@RequestParam String title, @RequestParam String author) {
 		// @ResponseBody means the returned String is the response, not a view Title
 		// @RequestParam means it is a parameter from the GET or POST request

 		Books n = new Books();
 		n.setTitle(title);
 		n.setAuthor(author);
 		booksRepository.save(n);
 		return "Saved";
 	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Books> getAllBooks() {
		// This returns a JSON or XML with the users
		return booksRepository.findAll();
	}
	
	@RequestMapping("/home")
	public String test() {
		return "index";
	}
}
